"""Import HumanEval dataset and generate FormicOS eval task configs.

Downloads the HumanEval dataset from the openai/human-eval GitHub repo,
then generates 164 task YAML files in config/eval/tasks/humaneval/ plus
a suite config at config/eval/suites/humaneval.yaml.

Usage::

    python scripts/import_humaneval.py
    python scripts/import_humaneval.py --output-dir config/eval/tasks/humaneval
    python scripts/import_humaneval.py --dry-run

Requires: requests (or falls back to urllib).
"""

from __future__ import annotations

import argparse
import gzip
import json
import sys
from pathlib import Path

# HumanEval dataset URL (JSONL, gzipped)
_DATASET_URL = (
    "https://github.com/openai/human-eval/raw/master/data/HumanEval.jsonl.gz"
)

_TASKS_DIR = Path(__file__).resolve().parents[1] / "config" / "eval" / "tasks" / "humaneval"
_SUITES_DIR = Path(__file__).resolve().parents[1] / "config" / "eval" / "suites"


def _download_dataset(url: str) -> list[dict]:
    """Download and parse the HumanEval JSONL.gz dataset."""
    try:
        import httpx  # noqa: PLC0415

        resp = httpx.get(url, follow_redirects=True, timeout=30)
        resp.raise_for_status()
        raw = resp.content
    except ImportError:
        from urllib.request import urlopen  # noqa: PLC0415, S310

        with urlopen(url, timeout=30) as resp:  # noqa: S310
            raw = resp.read()

    decompressed = gzip.decompress(raw)
    problems = []
    for line in decompressed.decode("utf-8").strip().split("\n"):
        if line.strip():
            problems.append(json.loads(line))
    return problems


def _sanitize_id(task_id: str) -> str:
    """Convert HumanEval/N to he-N."""
    return task_id.replace("HumanEval/", "he-").replace("/", "-").lower()


def _generate_task_yaml(problem: dict) -> str:
    """Generate a FormicOS eval task YAML from a HumanEval problem."""
    task_id = _sanitize_id(problem["task_id"])
    prompt = problem["prompt"].strip()
    entry_point = problem["entry_point"]

    # The task description is the function signature + docstring
    # We escape it for YAML multi-line
    description = (
        f"Implement the following Python function. Return ONLY the complete "
        f"function implementation.\n\n{prompt}"
    )

    return (
        f"id: {task_id}\n"
        f"description: |\n"
        + "\n".join(f"  {line}" for line in description.split("\n"))
        + "\n"
        f"difficulty: moderate\n"
        f"category: humaneval\n"
        f"castes:\n"
        f"  - caste: coder\n"
        f"    tier: standard\n"
        f"    count: 1\n"
        f"success_rubric: |\n"
        f"  Function {entry_point} passes all HumanEval test cases.\n"
        f"  Implementation must be correct, handle edge cases, and match\n"
        f"  the expected function signature exactly.\n"
        f"budget_limit: 1.00\n"
        f"max_rounds: 3\n"
        f"# HumanEval metadata\n"
        f"humaneval_task_id: \"{problem['task_id']}\"\n"
        f"humaneval_entry_point: \"{entry_point}\"\n"
    )


def _generate_suite_yaml(task_ids: list[str]) -> str:
    """Generate the humaneval suite config."""
    task_lines = "\n".join(f"  - {tid}" for tid in task_ids)
    return (
        "# HumanEval Benchmark Suite — Wave 60\n"
        "#\n"
        "# Standard HumanEval pass@1 benchmark (164 problems).\n"
        "# Single-colony execution: 1 coder, sequential, 3 rounds.\n"
        "# Quality evaluated post-colony via test case execution.\n"
        "#\n"
        "# Generated by scripts/import_humaneval.py\n"
        "\n"
        "task_order:\n"
        f"{task_lines}\n"
        "\n"
        "strategy: sequential\n"
        "budget_per_task: 1.00\n"
        "max_rounds_per_task: 3\n"
        "escalation_policy: none\n"
        "model_mix: {}\n"
        "knowledge_mode: empty\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Import HumanEval into FormicOS eval")
    parser.add_argument("--output-dir", type=Path, default=_TASKS_DIR)
    parser.add_argument("--suites-dir", type=Path, default=_SUITES_DIR)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--from-file", type=Path, default=None,
                        help="Load from local .jsonl.gz instead of downloading")
    args = parser.parse_args()

    # Load dataset
    if args.from_file:
        print(f"Loading from {args.from_file}")
        with open(args.from_file, "rb") as fh:
            raw = fh.read()
        if args.from_file.suffix == ".gz":
            raw = gzip.decompress(raw)
        else:
            raw = raw  # noqa: PLW0127
        problems = [json.loads(line) for line in raw.decode("utf-8").strip().split("\n") if line.strip()]
    else:
        print(f"Downloading HumanEval from {_DATASET_URL}")
        problems = _download_dataset(_DATASET_URL)

    print(f"Loaded {len(problems)} problems")

    if args.dry_run:
        for p in problems[:3]:
            print(f"\n--- {p['task_id']} ---")
            print(_generate_task_yaml(p)[:300])
        print(f"\n... and {len(problems) - 3} more")
        return

    # Create output directories
    args.output_dir.mkdir(parents=True, exist_ok=True)
    args.suites_dir.mkdir(parents=True, exist_ok=True)

    # Generate task configs
    task_ids = []
    for problem in problems:
        task_id = _sanitize_id(problem["task_id"])
        task_ids.append(task_id)
        task_yaml = _generate_task_yaml(problem)
        task_path = args.output_dir / f"{task_id}.yaml"
        task_path.write_text(task_yaml, encoding="utf-8")

    print(f"Generated {len(task_ids)} task configs in {args.output_dir}")

    # Generate suite config
    suite_yaml = _generate_suite_yaml(task_ids)
    suite_path = args.suites_dir / "humaneval.yaml"
    suite_path.write_text(suite_yaml, encoding="utf-8")
    print(f"Generated suite config at {suite_path}")

    # Save test cases for the evaluator
    test_cases_path = args.output_dir / "_test_cases.json"
    test_data = {}
    for problem in problems:
        task_id = _sanitize_id(problem["task_id"])
        test_data[task_id] = {
            "task_id": problem["task_id"],
            "entry_point": problem["entry_point"],
            "test": problem.get("test", ""),
            "prompt": problem["prompt"],
        }
    test_cases_path.write_text(json.dumps(test_data, indent=2), encoding="utf-8")
    print(f"Saved test cases to {test_cases_path}")


if __name__ == "__main__":
    main()
